# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0511b444348e3062f1285e976d88a7f103dd40e9f579b5df02f6bcb00843d7137caf5647d93e9f217bf6342979d5113b9d684cac83c5d97348d16d89dbdbe2a

test:
  secret_key_base: 498c03a824b7423bed06602248c8b45cb05363c18ebb5d6a9fb2346beca83ada177ecc05c0f18744c595737709f870da53eeec1347de8e6866081d66538ed767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
